name: Ruff Lint and Format Check

on:
  pull_request:
    paths:
      - "**.py"

jobs:
  ruff-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ruff using the extracted version
        run: pip install ruff==0.3.4

      - name: Get changed Python files
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          files: "**.py"

      - name: Run Ruff Format and Lint Check
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          ruff format --check --config ./pyproject.toml ${{ steps.changed-files.outputs.all_changed_files }}
          ruff check --config ./pyproject.toml ${{ steps.changed-files.outputs.all_changed_files }}
        continue-on-error: true

      - name: Report Ruff Check Status
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          if [ $? -ne 0 ]; then
            echo "Ruff checks failed. Please fix the issues and re-submit the pull request."
            exit 1
          else
            echo "Ruff checks passed successfully!"
          fi
